// Seed data for development/demo screenshots
// Run via a script or API route to populate demo data

export const seedRecords = [
  {
    type: 'condition',
    title: 'Type 2 Diabetes',
    description: 'Diagnosed during routine bloodwork. Managing with medication and lifestyle changes.',
    date: '2023-03-15',
    status: 'active',
    provider_name: 'Dr. Sarah Chen',
    specialty: 'Endocrinology',
    notes: 'HbA1c target < 7.0%. Last reading 6.8%.',
    metadata: {},
  },
  {
    type: 'condition',
    title: 'Hypertension',
    description: 'Stage 1 hypertension. Controlled with Lisinopril.',
    date: '2022-08-20',
    status: 'active',
    provider_name: 'Dr. Michael Torres',
    specialty: 'Cardiology',
    notes: 'Target BP < 130/80',
    metadata: {},
  },
  {
    type: 'condition',
    title: 'Generalized Anxiety Disorder',
    description: 'Managing with therapy and medication.',
    date: '2021-06-10',
    status: 'active',
    provider_name: 'Dr. Emily Park',
    specialty: 'Psychiatry',
    notes: 'Weekly CBT sessions. Stable on current medication.',
    metadata: {},
  },
  {
    type: 'medication',
    title: 'Metformin 500mg',
    description: 'For Type 2 Diabetes management',
    date: '2023-03-15',
    status: 'active',
    provider_name: 'Dr. Sarah Chen',
    specialty: 'Endocrinology',
    metadata: { dosage: '500mg', frequency: 'Twice daily with meals' },
  },
  {
    type: 'medication',
    title: 'Lisinopril 10mg',
    description: 'ACE inhibitor for blood pressure control',
    date: '2022-08-20',
    status: 'active',
    provider_name: 'Dr. Michael Torres',
    specialty: 'Cardiology',
    metadata: { dosage: '10mg', frequency: 'Once daily' },
  },
  {
    type: 'medication',
    title: 'Sertraline 50mg',
    description: 'SSRI for anxiety management',
    date: '2021-06-10',
    status: 'active',
    provider_name: 'Dr. Emily Park',
    specialty: 'Psychiatry',
    metadata: { dosage: '50mg', frequency: 'Once daily in morning' },
  },
  {
    type: 'visit',
    title: 'Cardiology Follow-up',
    description: 'Routine follow-up for hypertension management. BP well-controlled.',
    date: '2025-12-15',
    status: 'resolved',
    provider_name: 'Dr. Michael Torres',
    specialty: 'Cardiology',
    notes: 'BP 125/78. Continue current medication. Follow up in 6 months.',
    metadata: {},
  },
  {
    type: 'visit',
    title: 'Endocrinology Check-up',
    description: 'Quarterly diabetes review.',
    date: '2025-11-20',
    status: 'resolved',
    provider_name: 'Dr. Sarah Chen',
    specialty: 'Endocrinology',
    notes: 'HbA1c 6.8% — good control. Continue Metformin.',
    metadata: {},
  },
  {
    type: 'lab',
    title: 'Comprehensive Metabolic Panel',
    description: 'Routine bloodwork',
    date: '2025-11-18',
    status: 'resolved',
    provider_name: 'Quest Diagnostics',
    specialty: 'Primary Care',
    metadata: { lab_name: 'Quest Diagnostics', key_values: 'Glucose: 115, Creatinine: 0.9, BUN: 15', reference_range: 'Glucose: 70-100' },
  },
  {
    type: 'lab',
    title: 'HbA1c Test',
    description: 'Diabetes monitoring',
    date: '2025-11-18',
    status: 'resolved',
    provider_name: 'Dr. Sarah Chen',
    specialty: 'Endocrinology',
    metadata: { lab_name: 'LabCorp', key_values: 'HbA1c: 6.8%', reference_range: 'Normal: < 5.7%, Prediabetic: 5.7-6.4%, Diabetic: > 6.5%' },
  },
  {
    type: 'imaging',
    title: 'Chest X-Ray',
    description: 'Routine pre-procedure screening',
    date: '2025-09-05',
    status: 'resolved',
    provider_name: 'Dr. James Wilson',
    specialty: 'Radiology',
    metadata: { imaging_type: 'X-Ray', body_region: 'Chest', findings: 'No acute cardiopulmonary disease.' },
  },
  {
    type: 'vaccination',
    title: 'Influenza Vaccine (2025-2026)',
    description: 'Annual flu shot',
    date: '2025-10-01',
    status: 'resolved',
    provider_name: 'CVS Pharmacy',
    specialty: 'Primary Care',
    metadata: {},
  },
  {
    type: 'vaccination',
    title: 'COVID-19 Booster',
    description: 'Updated booster shot',
    date: '2025-09-15',
    status: 'resolved',
    provider_name: 'CVS Pharmacy',
    specialty: 'Primary Care',
    metadata: {},
  },
];

export const seedProviders = [
  {
    name: 'Dr. Sarah Chen',
    specialty: 'Endocrinology',
    clinic_name: 'Metro Endocrine Associates',
    email: 'schen@metroendocrine.com',
    phone: '(555) 234-5678',
    has_access: true,
    access_level: 'relevant' as const,
  },
  {
    name: 'Dr. Michael Torres',
    specialty: 'Cardiology',
    clinic_name: 'Heart & Vascular Center',
    email: 'mtorres@heartcenter.com',
    phone: '(555) 345-6789',
    has_access: true,
    access_level: 'full' as const,
  },
  {
    name: 'Dr. Emily Park',
    specialty: 'Psychiatry',
    clinic_name: 'Clarity Mental Health',
    email: 'epark@clarityhealth.com',
    phone: '(555) 456-7890',
    has_access: true,
    access_level: 'relevant' as const,
  },
  {
    name: 'Dr. Robert Kim',
    specialty: 'Primary Care',
    clinic_name: 'Downtown Family Practice',
    email: 'rkim@downtownfp.com',
    phone: '(555) 567-8901',
    has_access: false,
    access_level: 'summary_only' as const,
  },
];

export const seedProfile = {
  full_name: 'Alex Johnson',
  date_of_birth: '1995-07-14',
  blood_type: 'O+' as const,
  allergies: ['Penicillin', 'Shellfish'],
  emergency_contact_name: 'Maria Johnson',
  emergency_contact_phone: '(555) 123-4567',
  onboarding_completed: true,
};
